version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - book_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - book_network

volumes:
  postgres_data:
  redis_data:

networks:
  book_network:
    driver: bridge